use pkg-config

diff --git a/r/adbcpostgresql/configure b/r/adbcpostgresql/configure
--- a/r/adbcpostgresql/configure
+++ b/r/adbcpostgresql/configure
@@ -28,14 +28,25 @@ fi
 # Include and library flags
 PKG_LIBS="$PKG_LIBS"
 
+# Check for pkg-config
+HAS_PKG_CONFIG=""
+pkg-config libpq --exists
+if [ $? -eq 0 ]; then
+  HAS_PKG_CONFIG=true
+fi
+
 echo "Checking for --configure-vars INCLUDE_DIR or LIB_DIR"
 if [ "$INCLUDE_DIR" ] || [ "$LIB_DIR" ]; then
   echo "Found --configure-vars INCLUDE_DIR and/or LIB_DIR"
   PKG_CPPFLAGS="-I$INCLUDE_DIR $PKG_CPPFLAGS"
   PKG_LIBS="-L$LIB_DIR $PKG_LIBS"
+elif [ ! -z "$HAS_PKG_CONFIG" ]; then
+  echo "Using pkg-config libpq"
+  PKG_CPPFLAGS="`pkg-config libpq --cflags` $PKG_CPPFLAGS"
+  PKG_LIBS="`pkg-config libpq --libs` -lpq $PKG_LIBS"
 else
-  PKG_CPPFLAGS="-I`pg_config --includedir` $PKG_CPPFLAGS"
-  PKG_LIBS="-L`pg_config --libdir` -lpq $PKG_LIBS"
+  echo "INCLUDE_DIR/LIB_DIR and pkg-config not found; trying PKG_LIBS=-lpq"
+  PKG_LIBS="-lpq"
 fi
 
 echo "Testing R CMD SHLIB with $PKG_CPPFLAGS $PKG_LIBS"
